version: 2

defaults: &defaults
  working_directory: ~/website

jobs:
  build:
    <<: *defaults

    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "src/website/yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: cd src/website && yarn install
      - run: cd src/website && yarn build
      - run: cd src/website && yarn export

      - save_cache:
          key: v2-dependencies-{{ checksum "src/website/yarn.lock" }}
          paths:
            - src/website/node_modules

      - persist_to_workspace:
          root: ~/website
          paths:
            - src/website/out/*

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/website

      - run: ls -al && aws --version

workflows:
  version: 2

  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
