version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/website

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/website/yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd src/website && yarn install

      - save_cache:
          key: v1-dependencies-{{ checksum "src/website/yarn.lock" }}
          paths:
            - src/website/node_modules
