version: 2

defaults: &defaults
  working_directory: ~/website

jobs:
  build:
    <<: *defaults

    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: yarn install
      - run: yarn build
      - run: yarn export

      - save_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/website
          paths:
            - out/*

  deploy:
    <<: *defaults

    docker:
      - image: cibuilds/aws

    steps:
      - attach_workspace:
          at: ~/website

      - run: |
          aws s3 sync out/ s3://vladholubiev.com --acl public-read --cache-control "public, max-age=31536000" --exclude '*.html'
          aws s3 sync out/ s3://vladholubiev.com --acl public-read --cache-control "no-cache" --exclude '*' --include '*.html'

workflows:
  version: 2

  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
