version: 2
jobs:
  deploy_website:
    docker:
      - image: circleci/node:8

    working_directory: ~/website

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "src/website/yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: cd src/website && yarn install
      - run: cd src/website && yarn build
      - run: cd src/website && yarn export
      - run: cd src/website && aws --version

      - save_cache:
          key: v2-dependencies-{{ checksum "src/website/yarn.lock" }}
          paths:
            - src/website/node_modules
